services:
  # PostgreSQL Database
  postgres:
    image: postgres:17.5
    container_name: nextjs-starter-db-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: my_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Next.js Application (Production)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-starter-app-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@postgres:5432/my_app_db
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=my_app_db
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data_prod:

networks:
  app-network:
    driver: bridge
